@baseURL = http://localhost:3030

###WELCOME
GET {{baseURL}}


#########AUTH
### POST register doctor
POST {{baseURL}}/auth/register/doctor
Content-Type: application/json

{
  "username": "dr_PPich",
  "password": "password",
  "specialization": "Cardiologist"
}

### POST register user
POST {{baseURL}}/auth/register/user
Content-Type: application/json

{
  "username": "Peachayapa",
  "password": "password"
}

### POST login doctor
POST {{baseURL}}/auth/login/doctor
Content-Type: application/json

{
  "username": "dr_PPich",
  "password": "password"
}

### POST login user
POST {{baseURL}}/auth/login/user
Content-Type: application/json

{
  "username": "Peachayapa",
  "password": "password"
}




#########Users Doctors
@tokenUser = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJQZWFjaGF5YXBhIiwiaWF0IjoxNzcyNzkwODM1LCJleHAiOjE3NzUzODI4MzV9.w5UOORCH7o7cLZfrSDpJUoLyyOQk9Bk0mfOF7OcwjOo

@tokenDoctor = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJkcl9QUGljaCIsImlhdCI6MTc3Mjc4ODcxMSwiZXhwIjoxNzc1MzgwNzExfQ.70vyl-3z__Nnfa7KMeTtYw8foudBUMYMZeeYDRGoYxI

### GET users
GET {{baseURL}}/users/me
Content-Type: application/json
Authorization: Bearer {{tokenUser}}

### PUT users
PUT {{baseURL}}/users/me
Content-Type: application/json
Authorization: Bearer {{tokenUser}}

{
  "username": "PeachPUTneww",
  "password": "newpass"
}

### GET doctors
GET {{baseURL}}/doctors/me
Content-Type: application/json
Authorization: Bearer {{tokenDoctor}}

### PUT doctors
PUT {{baseURL}}/doctors/me
Content-Type: application/json
Authorization: Bearer {{tokenDoctor}}

{
  "username": "DR_PeachPUTnew",
  "password": "newpass",
  "specialization": "Archi"
}



#########Health Records
### POST Health Records
POST {{baseURL}}/health-records
Content-Type: application/json
Authorization: Bearer {{tokenUser}}

{
  "type": "Diabetes",
  "value": "120/80 mmHg"
}

###GET HR
GET {{baseURL}}/health-records
Content-Type: application/json
Authorization: Bearer {{tokenUser}}